name: sikomik
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.8
  flutter_image: ^4.1.11
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_it: ^8.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  responsive_framework: ^1.5.1
  toastification: ^2.3.0
  url_strategy: ^0.3.0
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
#  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter_app_name:
  name: "Si Komik"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/ic_launcher.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/ic_launcher.png"
  windows:
    generate: true
    image_path: "images/ic_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - images/
