name: si_komik
description: A new Flutter project.
publish_to: 'none'

version: 1.2.7+20

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter_rating_bar: ^4.0.1
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.12
  flutter_inappwebview: ^6.1.5
  font_awesome_flutter: ^10.8.0
  get: ^5.0.0-release-candidate-9.3.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  responsive_framework: ^1.5.1
  toastification: ^3.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.3
  change_app_package_name: ^1.5.0
  firebase_auth_mocks: ^0.14.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  google_sign_in_mocks: ^0.3.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  rename_app: ^1.6.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/ic_launcher.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/ic_launcher.png"
  windows:
    generate: true
    image_path: "images/ic_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - images/
