name: sikomik
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.5.0
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  responsive_framework: ^1.1.0
  url_strategy: ^0.2.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
#  change_app_package_name: ^1.1.0
#  flutter_app_name: ^0.1.0
#  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.0

flutter_app_name:
  name: "Si Komik"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:

  uses-material-design: true
