name: sikomik
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  flutter_rating_bar: ^4.0.1
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.8
  flutter_inappwebview: ^6.1.5
  flutter_image: ^4.1.11
  font_awesome_flutter: ^10.8.0
  get: ^5.0.0-release-candidate-9.2.1
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  responsive_framework: ^1.5.1
  toastification: ^2.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  change_app_package_name: ^1.4.0
#  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0

flutter_app_name:
  name: "Si Komik"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "images/ic_launcher.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/ic_launcher.png"
  windows:
    generate: true
    image_path: "images/ic_launcher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/ic_launcher.png"

flutter:
  uses-material-design: true

  assets:
    - images/
