name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/cirruslabs/flutter:stable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Clean Dependencies
      run: flutter clean

    - name: Install Dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cirruslabs/flutter:stable
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Clean Dependencies
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: /
